<style scoped>
p {
	margin-bottom: 8px;
}
p:last-child {
	margin-bottom: 0;
}
</style>

<template>
	<v-card>
		<v-card-title>
			<v-icon small class="mr-1">info</v-icon> Job Information
		</v-card-title>

		<v-card-text class="pt-0">
			<v-layout column class="list">
				<v-flex tag="p">
					<strong>Height:</strong> {{ $displayZ(jobFile.height) }}
				</v-flex>
				<v-flex tag="p" v-if="!mode || mode === 'FFF'">
					<strong>Layer Height:</strong> {{ $displayZ(jobFile.layerHeight) }}
				</v-flex>
				<v-flex tag="p" v-if="!mode || mode === 'FFF'">
					<strong>Filament Usage:</strong> {{ $displayZ(jobFile.filamentNeeded, 'mm') }}
				</v-flex>
				<v-flex tag="p">
					<strong>Generated by:</strong> {{ $display(jobFile.generatedBy) }}
				</v-flex>
			</v-layout>
		</v-card-text>
	</v-card>

</template>

<script>
'use strict'

import { mapState } from 'vuex'

export default {
	computed: {
		...mapState('machine/model', {
			mode: state => state.state.mode,
			jobFile: state => state.job.file
		})
	}
}
</script>
