<style scoped>
p {
	margin-bottom: 8px;
}
p:last-child {
	margin-bottom: 0;
}
</style>

<template>
	<v-card>
		<v-card-title>
			<v-icon small class="mr-1">info</v-icon> Job Information
		</v-card-title>

		<v-card-text class="pt-0">
			<v-layout column class="list">
				<v-flex tag="p">
					<strong>Filename:</strong> {{ $display(filename) }}
				</v-flex>
				<v-flex tag="p">
					<strong>Height:</strong> {{ $displayZ(job.height) }}
				</v-flex>
				<v-flex tag="p" v-if="!state.mode || state.mode === 'FFF'">
					<strong>Layer Height:</strong> {{ $displayZ(job.height) }}
				</v-flex>
				<v-flex tag="p" v-if="!state.mode || state.mode === 'FFF'">
					<strong>Filament Usage:</strong> {{ $displayZ(job.filamentUsage, 'mm') }}
				</v-flex>
				<v-flex tag="p">
					<strong>Generated by:</strong> {{ $display(job.generatedBy) }}
				</v-flex>
			</v-layout>
		</v-card-text>
	</v-card>

</template>

<script>
'use strict'

import { mapState } from 'vuex'

import { extractFileName } from '../../utils/path.js'

export default {
	computed: {
		...mapState('machine', ['state', 'job']),
		filename() { return this.job.filename && extractFileName(this.job.filename); }
	}
}
</script>
