/**
 * plugins/index.ts
 *
 * DWC Plugin Loader
 *
 * Handles loading both built-in and external plugins:
 *
 * Built-in plugins are part of the same Vite build. They are auto-discovered
 * at build time by vite-plugin-dwc-plugins and lazily imported. Because they
 * share the module graph, they simply import what they need directly:
 *
 *   import { registerRoute } from "@/plugins";
 *   import MyPage from "./MyPage.vue";
 *   registerRoute(MyPage, { Plugins: { MyPage: { icon: "mdi-...", caption: "...", path: "/Plugins/MyPage" } } });
 *
 * External plugins are precompiled IIFE bundles fetched at runtime from the
 * machine. They are built with DWC's shared libraries marked as externals,
 * mapped to `window.DWC`. This lets them use the same API:
 *
 *   const { registerRoute } = DWC;
 *   registerRoute(MyPage, { ... });
 *
 * The global `window.DWC` object is set up by `initPluginSystem()` and exposes
 * the plugin registration functions, stores, Vue, vue-router, and i18n.
 */

import { setupLayouts } from "virtual:generated-layouts";
import type { App, Component } from "vue";
import type { RouteRecordRaw, Router } from "vue-router";
import { type ModelCollection, SbcPermission } from "@duet3d/objectmodel";

import type DwcPlugin from "./DwcPlugin";
import type { ContextMenuItem } from "@/stores/ui";
import router from "@/router";

export { registerLayout, unregisterLayout } from "./layout";
export type { RegisterLayoutOptions } from "./layout";

export { getPageComponent } from "@/router/pages";

export { registerTheme, unregisterTheme } from "./theme";
export type { RegisterThemeDefinition, RegisteredTheme } from "./theme";

import { exposeGlobalAPI } from "./global-api";

import * as Vue from "vue";

// @ts-ignore - virtual module generated by vite/dwc-plugins, replacement for "imports.ts"
import plugins from "virtual:dwc-builtin-plugins";

// Static set of Vuetify components DWC's own templates use. The import lands them in the
// app chunk (vite-plugin-vuetify's per-file autoImport is off) and `app.component()` below
// registers them globally so any template - including dynamically-loaded plugin templates -
// can resolve <v-foo> tags by name. DWC's own components and the Vuetify extras (components
// only external plugins might need) are pulled in lazily via virtual:dwc-components and
// virtual:dwc-vuetify-extras so they don't get yanked into the main bundle for users who
// never load a plugin
import vuetifyCoreComponents from "virtual:dwc-vuetify-core";

import Events from "@/utils/events";
import { samePluginId } from "@/utils/plugins";
import i18n from "@/i18n";

import { useSettingsStore } from "@/stores/settings";
import { useMachineStore } from "@/stores/machine";
import { useMenuStore } from "@/stores/menu";
import { useUiStore, ContextMenuType } from "@/stores/ui";

import packageInfo from "../../package.json";

// #region Built-in plugin registry
const builtInPlugins: ModelCollection<DwcPlugin> = plugins;

// #endregion

// #region Manifest validation
/**
 * Validate a plugin manifest.
 * @param manifest Plugin manifest to check
 * @returns Whether the manifest is valid
 */
export function checkManifest(manifest: { id: string; name: string; author: string; version: string; sbcPermissions?: Iterable<string> }): boolean {
	if (!manifest.id || manifest.id.trim() === "" || manifest.id.length > 32) {
		console.warn("Invalid plugin identifier");
		return false;
	}
	if (manifest.id.split("").some(c => !/[a-zA-Z0-9 .\-_]/.test(c))) {
		console.warn("Illegal plugin identifier");
		return false;
	}
	if (!manifest.name || manifest.name.trim() === "" || manifest.name.length > 64) {
		console.warn("Invalid plugin name");
		return false;
	}
	if (manifest.name.split("").some(c => !/[a-zA-Z0-9 .\-_]/.test(c))) {
		console.warn("Illegal plugin name");
		return false;
	}
	if (!manifest.author || manifest.author.trim() === "") {
		console.warn("Missing author");
		return false;
	}
	if (!manifest.version || manifest.version.trim() === "") {
		console.warn("Missing version");
		return false;
	}
	if (manifest.sbcPermissions) {
		const supported = Object.keys(SbcPermission);
		for (const permission of manifest.sbcPermissions) {
			if (!supported.includes(permission)) {
				console.warn(`Unsupported SBC permission ${permission}`);
				return false;
			}
		}
	}
	return true;
}

/**
 * Perform a version compatibility check.
 * Compares version segments up to the shorter of the two strings.
 * @param actual Actual version (e.g. "3.6.0")
 * @param required Required version (e.g. "3.6")
 * @returns Whether the actual version satisfies the required version
 */
export function checkVersion(actual: string, required: string): boolean {
	if (!required) {
		return true;
	}
	const actualParts = actual.split(/[+.\-ab]/);
	const requiredParts = required.split(/[+.\-ab]/);
	for (let i = 0; i < Math.min(actualParts.length, requiredParts.length); i++) {
		if (actualParts[i] !== requiredParts[i]) {
			return false;
		}
	}
	return true;
}

// #endregion

// #region State
/**
 * Set of currently loaded plugin IDs
 */
const loadedPlugins = new Set<string>();

/**
 * Vue Router instance, set during initialisation
 */
// Router is imported directly at module load instead of being injected via initPluginSystem
// Earlier we had a race where loadDwcPlugins() (called from machine.connect during HMR-driven
// reconnects) ran before registerPlugins had a chance to call initPluginSystem, causing
// "Plugin system not initialised" to throw out of registerRoute. Importing the singleton at
// module load eliminates the window
let _router: Router | null = router;

/**
 * Menu categories registered by plugins
 */
export interface MenuCategory {
	icon: string;
	caption: string | (() => string);
	translated: boolean;
	pages: Array<MenuItem>;
}

/**
 * Menu item registered by a plugin
 */
export interface MenuItem {
	icon: string;
	caption: string | (() => string);
	path: string;
	component: Component;
	translated?: boolean;
	condition?: boolean | (() => boolean);
}

const _menuCategories = new Map<string, MenuCategory>();

/**
 * Per-path cleanup functions returned by `router.addRoute()` at registration time, used by
 * {@link unregisterRoute} to tear down a previously-registered route without leaking matchers
 */
const _routeRemovers = new Map<string, Array<() => void>>();

// Bare (unwrapped) route records registered by plugins, exposed via the read-only
// {@link registeredRoutes} export. A third-party custom layout that runs its own vue-router can
// read this to mount plugin pages inside its own layout shell instead of DWC's default one - the
// records carry no layout wrapper, only path/component/meta. shallowReactive so a layout that
// watches the list stays in sync as plugins load/unload at runtime; the nested route objects are
// stored as-is (not proxied), keeping the component references referential. Keyed privately by the
// registration path so {@link unregisterRoute} can drop the matching entry even when the route uses
// a parametrised `routePath` that differs from its navigation `path`
const _registeredRoutes = Vue.shallowReactive<Array<RouteRecordRaw>>([]);
const _registeredRoutesByPath = new Map<string, RouteRecordRaw>();

/**
 * Read-only list of plugin-registered routes (bare, before default-layout wrapping). Lets a
 * third-party custom layout add plugin pages to its own router
 */
export const registeredRoutes = _registeredRoutes as ReadonlyArray<RouteRecordRaw>;

/**
 * Settings-page tab contributed by a plugin via {@link registerSettingTab}
 */
export interface SettingTab {
	/**
	 * Stable identifier used as the v-tabs / v-window value
	 */
	key: string;

	/**
	 * Material Design icon
	 */
	icon: string;

	/**
	 * Caption - by default an i18n key; when {@link translated} is true, used verbatim
	 */
	caption: string | (() => string);

	/**
	 * Treat {@link caption} as a literal string instead of an i18n key
	 */
	translated?: boolean;

	/**
	 * Vue component to render inside the tab's v-window-item
	 */
	component: Component;

	/**
	 * Sort order relative to built-in + other plugin tabs (lower = leftmost; defaults to 100)
	 */
	order?: number;
}

// Reactive array so Settings.vue picks up new tabs as they're registered. shallowReactive
// (not reactive) is deliberate: only array-level changes (push/splice) need tracking, and
// deep-tracking each entry would proxy the stored Component reference - which Vue
// explicitly warns about (components are referential, not state)
const _settingTabs = Vue.shallowReactive<Array<SettingTab>>([]);

/**
 * Read-only view of plugin-registered Settings tabs. Settings.vue consumes this and merges
 * the entries with its built-in tab list, ordering by `order ?? 100`
 */
export function getPluginSettingTabs(): ReadonlyArray<SettingTab> {
	return _settingTabs as ReadonlyArray<SettingTab>;
}

/**
 * Job-view panel tab contributed by a plugin via {@link registerJobViewTab}. The Job Status
 * page's tabbed view panel merges these with its built-in tabs (layer chart, G-code stream)
 */
export interface JobViewTab {
	/**
	 * Stable identifier used to track and persist the active tab
	 */
	key: string;

	/**
	 * Material Design icon
	 */
	icon: string;

	/**
	 * Caption - by default an i18n key; when {@link translated} is true, used verbatim
	 */
	caption: string | (() => string);

	/**
	 * Treat {@link caption} as a literal string instead of an i18n key
	 */
	translated?: boolean;

	/**
	 * Vue component rendered as the tab's content
	 */
	component: Component;

	/**
	 * Sort order relative to built-in + other plugin tabs (lower = leftmost; defaults to 100)
	 */
	order?: number;

	/**
	 * Optional visibility predicate - a tab whose condition is false is hidden entirely.
	 * Useful for tabs that only apply to certain machine modes
	 */
	condition?: boolean | (() => boolean);
}

// shallowReactive for the same reason as _settingTabs: only push/splice need tracking, and
// deep-proxying would walk the stored Component reference
const _jobViewTabs = Vue.shallowReactive<Array<JobViewTab>>([]);

/**
 * Read-only view of plugin-registered Job-view tabs, consumed by the Job Status view panel
 */
export function getJobViewTabs(): ReadonlyArray<JobViewTab> {
	return _jobViewTabs as ReadonlyArray<JobViewTab>;
}

// #endregion

// #region Initialisation
/**
 * Initialise the plugin system. Must be called once during app startup
 * before any plugins are loaded.
 *
 * Sets up the global `window.DWC` object so that external plugins can
 * access DWC APIs at runtime, and registers the public DWC component
 * palette + Vuetify components used by core globally on the app so
 * external plugin templates can resolve them by name.
 *
 * @param app Vue app instance
 * @param router Vue Router instance
 */
export function initPluginSystem(app: App, router: Router) {
	_app = app;
	_router = router;
	// Vuetify core components (the subset DWC's own templates use) are eager - they're already
	// in the main bundle anyway, registering them globally so plugin templates can resolve
	// `<v-foo>` by name costs nothing. The Vuetify extras + DWC's own components load lazily
	// on first external-plugin arrival via ensurePluginExtras()
	for (const [name, component] of Object.entries(vuetifyCoreComponents)) {
		app.component(name, component);
	}
	exposeGlobalAPI();
}

let _app: App | null = null;
let _pluginExtrasLoaded = false;

/**
 * Lazy one-shot: load + globally register the Vuetify components NOT referenced anywhere
 * under src/, plus every DWC component under src/components/. Triggered on the first
 * external-plugin load so users with no external plugins never pay for the extras chunks.
 */
async function ensurePluginExtras(): Promise<void> {
	if (_pluginExtrasLoaded || !_app) {
		return;
	}
	_pluginExtrasLoaded = true;

	const [vuetifyExtrasMod, dwcComponentsMod] = await Promise.all([
		import("virtual:dwc-vuetify-extras"),
		import("virtual:dwc-components"),
	]);

	for (const [name, component] of Object.entries(vuetifyExtrasMod.default)) {
		_app.component(name, component);
	}
	for (const [name, component] of Object.entries(dwcComponentsMod.default)) {
		_app.component(name, component);
	}

	// Surface on window.DWC so plugins built with explicit imports resolve at runtime:
	//   import { VFoo } from "vuetify/components"          -> DWC.VuetifyComponents.VFoo
	//   import { FileList } from "DuetWebControl/components" -> DWC.Components.FileList
	// Fill the maps in place rather than reassigning: window.DWC is frozen after exposeGlobalAPI,
	// so its top-level keys can't be replaced - but the nested maps stay mutable (shallow freeze)
	const dwc = window.DWC;
	if (dwc) {
		Object.assign(dwc.VuetifyComponents, vuetifyExtrasMod.default);
		Object.assign(dwc.Components, dwcComponentsMod.default);
	}
}

// #endregion

// #region Plugin registration API
// These functions are called directly by plugins (both built-in and external)

/**
 * Register a new route and menu item.
 *
 * Call shape:
 *   registerRoute(Component, { CategoryName: { PageName: { icon, caption, path, condition? } } })
 *
 * @param component Vue component to render
 * @param route Route descriptor: { [category]: { [name]: { icon, caption, path, condition?, translated? } } }
 */
export function registerRoute(
	component: Component,
	route: Record<string, Record<string, { icon: string; caption: string | (() => string); path: string; routePath?: string; condition?: boolean | (() => boolean); translated?: boolean; order?: number; pageFill?: boolean; scrollToBottom?: boolean }>>
) {
	if (!_router) {
		throw new Error("Plugin system not initialised");
	}

	const category = Object.keys(route)[0];
	const name = Object.keys(route[category])[0];
	const descriptor = route[category][name];

	// Build menu item
	const menuItem: MenuItem = {
		icon: descriptor.icon,
		caption: descriptor.caption,
		path: descriptor.path,
		component,
		translated: descriptor.translated ?? false,
		condition: descriptor.condition ?? true,
	};

	// Ensure category exists
	if (!_menuCategories.has(category)) {
		_menuCategories.set(category, {
			icon: "mdi-puzzle",
			caption: `menu.${category.toLowerCase()}.caption`,
			translated: false,
			pages: [],
		});
	}

	// Add to category
	_menuCategories.get(category)!.pages.push(menuItem);

	// setupLayouts wraps the bare route in the default layout (app bar + nav drawer + status row),
	// matching how the static file-based routes get composed at boot. Without this, plugin pages
	// render their component in isolation and lose the entire shell.
	// `routePath` lets a plugin register a parametrised matcher (e.g. a trailing file path) while
	// the navigation drawer entry still points at the bare `path`; it defaults to `path`
	// `pageFill` marks a page that fills the viewport, which scrollBehavior reads to decide
	// whether bottom-anchoring on navigation applies. `scrollToBottom` additionally asks the
	// router to scroll the page to its bottom edge on open (viewer-style pages)
	const baseRoute = {
		path: descriptor.routePath ?? descriptor.path,
		component,
		meta: { pageFill: descriptor.pageFill === true, scrollToBottom: descriptor.scrollToBottom === true },
	} as RouteRecordRaw;
	const wrapped = setupLayouts([baseRoute]);
	const removers: Array<() => void> = [];
	for (const route of wrapped) {
		removers.push(_router.addRoute(route));
	}
	_routeRemovers.set(descriptor.path, removers);
	_registeredRoutesByPath.set(descriptor.path, baseRoute);
	_registeredRoutes.push(baseRoute);

	// Surface the item in the navigation drawer. The menu store is the single source the shell
	// reads from; category keys there are lowercase, hence the .toLowerCase() bridge to the
	// caller's PascalCase descriptor convention (kept for plugin-author compatibility)
	const caption = typeof descriptor.caption === "string"
		? descriptor.caption
		: descriptor.caption();
	const condition = descriptor.condition;
	useMenuStore().registerItem({
		category: category.toLowerCase(),
		icon: descriptor.icon,
		caption,
		translated: descriptor.translated ?? false,
		path: descriptor.path,
		order: descriptor.order,
		condition: typeof condition === "function" ? condition : undefined
	});
}

/**
 * Tear down a route previously added via {@link registerRoute}. Removes the route from vue-router
 * via the cleanup functions returned by `router.addRoute()` and drops the matching navigation
 * drawer entry. No-op when the path was never registered.
 *
 * @param path The same `path` value passed to {@link registerRoute}
 */
export function unregisterRoute(path: string) {
	const removers = _routeRemovers.get(path);
	if (removers) {
		for (const remove of removers) {
			remove();
		}
		_routeRemovers.delete(path);
	}
	const registered = _registeredRoutesByPath.get(path);
	if (registered) {
		_registeredRoutesByPath.delete(path);
		const idx = _registeredRoutes.indexOf(registered);
		if (idx !== -1) {
			_registeredRoutes.splice(idx, 1);
		}
	}
	useMenuStore().unregisterItem(path);
}

/**
 * Register a new menu category
 * @param name Internal name of the category
 * @param icon MDI icon string
 * @param caption Display caption (i18n key or getter function)
 * @param translated Whether the caption is already translated
 */
export function registerCategory(name: string, icon: string, caption: string | (() => string), translated = false) {
	if (!_menuCategories.has(name)) {
		_menuCategories.set(name, {
			icon,
			caption,
			translated,
			pages: [],
		});
	}
}

/**
 * Register a new Settings page tab.
 *
 * Plugins call this from their init code; the Settings page picks the new entry up via the
 * reactive {@link getPluginSettingTabs} read-side. Duplicate keys are ignored so a re-register
 * on hot reload doesn't end up with two copies.
 *
 * @param tab Tab descriptor: key, icon, caption (i18n key or literal), component, optional order
 */
export function registerSettingTab(tab: SettingTab) {
	if (_settingTabs.some((existing) => existing.key === tab.key)) {
		return;
	}
	// shallowReactive protects against deep-proxying the component, but mark it raw at the
	// registration site too so any downstream caller that re-wraps the tab (e.g. with
	// `reactive({ tabs })` in user code) still gets the un-proxied component reference
	_settingTabs.push({ ...tab, component: Vue.markRaw(tab.component) });
}

/**
 * Remove a previously registered Settings tab.
 * @param key Stable identifier passed to {@link registerSettingTab}
 */
export function unregisterSettingTab(key: string) {
	const idx = _settingTabs.findIndex((tab) => tab.key === key);
	if (idx !== -1) {
		_settingTabs.splice(idx, 1);
	}
}

/**
 * Register a new tab for the Job Status view panel.
 *
 * Lets a plugin contribute its own view of the running job (e.g. a 3D viewer) alongside the
 * built-in layer chart and G-code stream. Duplicate keys are ignored so a re-register on hot
 * reload doesn't end up with two copies.
 *
 * @param tab Tab descriptor: key, icon, caption, component, optional order and condition
 */
export function registerJobViewTab(tab: JobViewTab) {
	if (_jobViewTabs.some((existing) => existing.key === tab.key)) {
		return;
	}
	_jobViewTabs.push({ ...tab, component: Vue.markRaw(tab.component) });
}

/**
 * Remove a previously registered Job-view tab.
 * @param key Stable identifier passed to {@link registerJobViewTab}
 */
export function unregisterJobViewTab(key: string) {
	const idx = _jobViewTabs.findIndex((tab) => tab.key === key);
	if (idx !== -1) {
		_jobViewTabs.splice(idx, 1);
	}
}

/**
 * A component a plugin exposes for embedding in third-party flexible layouts. A layout lists these
 * in its "add widget" palette and renders the chosen one by {@link id}; a stored id whose plugin
 * isn't loaded lets the layout fall back to a "needs plugin" placeholder. Registered via
 * {@link registerEmbeddableComponent} and surfaced reactively on the UI store's `embeddableComponents`,
 * so a layout (built into its own bundle) reads them through `window.DWC` without importing internals
 */
export interface EmbeddableComponent {
	/** Stable, namespaced unique id a layout persists, e.g. "MyPlugin.PowerPanel" */
	id: string;

	/** Owning plugin id, so a shared layout can warn when the providing plugin is missing */
	pluginId: string;

	/** Palette label - an i18n key by default, or a literal when {@link translated} is true */
	caption: string | (() => string);

	/** Treat {@link caption} as a literal string instead of an i18n key */
	translated?: boolean;

	/** Material Design icon for the palette tile */
	icon?: string;

	/** Optional longer text shown in the palette preview */
	description?: string;

	/** Optional display metadata */
	author?: string;

	/** Component to render - markRaw'd at registration like layout / tab components */
	component: Component;

	/** Suggested initial grid footprint (columns x rows) so the widget lands at a sane size */
	defaultSize?: { w: number; h: number };

	/** Optional machine-mode filter, letting shells hide it like the built-in panels */
	machineMode?: "fff" | "cnc" | "any";
}

/**
 * Expose a component for embedding in third-party flexible layouts. Duplicate ids are ignored so a
 * re-register on hot reload doesn't end up with two copies. The component is markRaw'd before it
 * lands in the store so the store's deep reactivity never proxies it.
 *
 * @param definition Embeddable component descriptor; see {@link EmbeddableComponent}
 */
export function registerEmbeddableComponent(definition: EmbeddableComponent) {
	const uiStore = useUiStore();
	if (uiStore.embeddableComponents.some((existing) => existing.id === definition.id)) {
		return;
	}
	uiStore.embeddableComponents.push({ ...definition, component: Vue.markRaw(definition.component) });
}

/**
 * Remove a previously registered embeddable component.
 * @param id Stable id passed to {@link registerEmbeddableComponent}
 */
export function unregisterEmbeddableComponent(id: string) {
	const uiStore = useUiStore();
	const idx = uiStore.embeddableComponents.findIndex((entry) => entry.id === id);
	if (idx !== -1) {
		uiStore.embeddableComponents.splice(idx, 1);
	}
}

/**
 * Register a context menu item (e.g., on the job file list)
 * @param name Caption of the context menu item
 * @param path Optional route path to navigate to on click
 * @param icon MDI icon string
 * @param action Global event to trigger on click
 * @param contextMenuType Target of the context menu item
 */
export function registerPluginContextMenuItem(name: string | (() => string), path: string | undefined, icon: string, action: string, contextMenuType: ContextMenuType) {
	useUiStore().registerContextMenuItem({
		name,
		path,
		icon,
		action,
		contextMenuType,
	} as ContextMenuItem);
}

/**
 * Merge a plugin's locale messages into DWC's shared i18n instance under
 * `plugins.<pluginId>.*`. Pass a per-locale map - typically built from JSON
 * imports the plugin ships alongside its source:
 *
 * ```ts
 * import en from "./i18n/en.json";
 * import de from "./i18n/de.json";
 * registerPluginMessages("endstopsMonitor", { en, de });
 * // -> keys now resolvable as `plugins.endstopsMonitor.<key>` for every locale
 * ```
 *
 * Each call is additive - re-registering replaces only the leaf keys the new
 * map provides; other plugins' messages and DWC's own keys are untouched
 */
export function registerPluginMessages(pluginId: string, messagesPerLocale: Record<string, Record<string, unknown>>) {
	for (const [locale, messages] of Object.entries(messagesPerLocale)) {
		i18n.global.mergeLocaleMessage(locale, { plugins: { [pluginId]: messages } });
	}
}

// #endregion

// #region Query API
/**
 * Get all registered built-in plugin entries
 */
export function getBuiltInPlugins() {
	return builtInPlugins;
}

/**
 * Get the set of currently loaded plugin IDs
 */
export function getLoadedPlugins(): ReadonlySet<string> {
	return loadedPlugins;
}

/**
 * Check whether a plugin is currently loaded
 */
export function isPluginLoaded(id: string): boolean {
	return Array.from(loadedPlugins).some(p => samePluginId(p, id));
}

/**
 * Check whether a plugin is a built-in plugin
 */
export function isPluginBuiltIn(id: string): boolean {
	return builtInPlugins.some(p => samePluginId(p.id, id));
}

/**
 * Get all menu categories registered by plugins
 */
export function getMenuCategories(): ReadonlyMap<string, MenuCategory> {
	return _menuCategories;
}

// #endregion

// #region Loading
/**
 * Load and initialise a single DWC plugin by ID.
 *
 * Checks built-in plugins first, then falls back to external.
 *
 * @param id Plugin ID
 * @param saveSettings Whether to persist the enabled state
 */
export async function loadDwcPlugin(id: string, saveSettings = true): Promise<void> {
	if (isPluginLoaded(id)) {
		console.warn(`Plugin "${id}" is already loaded`);
		return;
	}

	const builtIn = builtInPlugins.find(p => samePluginId(p.id, id));
	if (builtIn) {
		await loadBuiltInPlugin(builtIn);
	} else if (import.meta.env.DEV) {
		// External plugins are served from the board's filesystem, which the dev server can't
		// provide, so fetching their JS/CSS would 404. Skip the load in dev rather than letting
		// every board-enabled plugin raise a spurious load failure
		console.warn(`Skipping external plugin "${id}": external plugins are only available in production builds`);
		return;
	} else {
		await loadExternalPlugin(id);
	}

	if (saveSettings) {
		useSettingsStore().dwcPluginLoaded(id);
	}

	Events.emit("dwcPluginLoaded", id);
}

/**
 * Load all enabled DWC plugins, reporting progress via events.
 */
export async function loadDwcPlugins(): Promise<void> {
	const settingsStore = useSettingsStore();

	if (settingsStore.enabledPlugins.length === 0) {
		// Still signal completion so listeners that wait on plugin loading (e.g. the Babylon
		// chunk prefetch) run even when there are no external plugins to load
		Events.emit("dwcPluginsLoaded", []);
		return;
	}

	Events.emit("dwcPluginsLoading", [...settingsStore.enabledPlugins]);

	for (const id of settingsStore.enabledPlugins) {
		try {
			await loadDwcPlugin(id, false);
		} catch (e) {
			console.warn(`Failed to load plugin "${id}":`, e);
			Events.emit("dwcPluginLoadError", { id, error: e });
		}
	}

	Events.emit("dwcPluginsLoaded", [...settingsStore.enabledPlugins]);
}

/**
 * Unload a plugin (best-effort - removes tracking and settings entry)
 * @param id Plugin ID
 */
export async function unloadDwcPlugin(id: string): Promise<void> {
	if (!isPluginLoaded(id)) {
		return;
	}

	for (const loaded of loadedPlugins) {
		if (samePluginId(loaded, id)) {
			loadedPlugins.delete(loaded);
		}
	}

	useSettingsStore().disableDwcPlugin(id);

	Events.emit("dwcPluginUnloaded", id);
}

// #endregion

// #region Built-in plugin loading
/**
 * Load a built-in plugin by executing its dynamic import.
 * The module's side effects handle all registration.
 */
async function loadBuiltInPlugin(plugin: DwcPlugin): Promise<void> {
	await plugin.loadDwcResources();
	loadedPlugins.add(plugin.id);
}

// #endregion

// #region External plugin loading
/**
 * Load an external plugin by fetching its JS/CSS from the machine.
 *
 * External plugins are IIFE bundles compiled with DWC's shared libraries
 * (vue, vue-router, pinia, DWC's own API) marked as externals. At runtime
 * those resolve to properties on `window.DWC`, so the plugin code can call
 * the same registration functions as built-in plugins.
 */
async function loadExternalPlugin(id: string): Promise<void> {
	// External plugin templates may use any Vuetify component (not just the subset DWC core
	// imports) and any DWC component (FileList, CodeButton, ...). Lazy-load + globally
	// register both extras chunks once, on first external load, so subsequent plugins
	// resolve them without re-fetching
	await ensurePluginExtras();

	const machineStore = useMachineStore();
	const machinePlugin = machineStore.model.plugins.get(id);

	if (!machinePlugin) {
		throw new Error(`Plugin "${id}" not found in built-in registry or machine plugins`);
	}

	// Validate manifest
	if (!checkManifest(machinePlugin)) {
		throw new Error(`Plugin "${id}" has an invalid manifest`);
	}

	// Version compatibility check
	if (machinePlugin.dwcVersion && !checkVersion(packageInfo.version, machinePlugin.dwcVersion)) {
		throw new Error(
			`Plugin "${id}" requires DWC version ${machinePlugin.dwcVersion}, ` +
			`current is ${packageInfo.version}`
		);
	}

	// Check dependencies
	for (const dep of machinePlugin.dwcDependencies) {
		if (!isPluginLoaded(dep)) {
			throw new Error(`Plugin "${id}" depends on "${dep}" which is not loaded`);
		}
	}

	// Separate JS and CSS files
	const jsFiles = machinePlugin.dwcFiles.filter((f: string) => f.endsWith(".js"));
	const cssFiles = machinePlugin.dwcFiles.filter((f: string) => f.endsWith(".css"));

	// SBC-only plugins (e.g. DuetPiManagementPlugin) have no DWC JS - that's a valid configuration,
	// the plugin runs entirely on the SBC. Treat the load as a no-op so it can still be marked
	// active and recorded in the loaded set; the caller may follow up with startSbcPlugin() to
	// actually launch the backend
	if (jsFiles.length === 0) {
		loadedPlugins.add(id);
		return;
	}

	const baseURL = import.meta.env.BASE_URL;

	// Load CSS first
	for (const cssFile of cssFiles) {
		await loadExternalCSS(id, baseURL + cssFile);
	}

	// Load and execute JS
	for (const jsFile of jsFiles) {
		await loadExternalJS(id, baseURL + jsFile);
	}

	loadedPlugins.add(id);
}

/**
 * Load a CSS file for an external plugin by injecting a <link> element.
 * The browser fetches the resource; the promise resolves/rejects via load/error events.
 */
function loadExternalCSS(pluginId: string, url: string): Promise<void> {
	return new Promise<void>((resolve, reject) => {
		const link = document.createElement("link");
		link.rel = "stylesheet";
		link.setAttribute("data-dwc-plugin", pluginId);
		link.href = url;
		link.onload = () => resolve();
		link.onerror = () => reject(new Error(`Failed to load CSS "${url}" for plugin "${pluginId}"`));
		document.head.appendChild(link);
	});
}

/**
 * Load a JS file for an external plugin by injecting a <script> element.
 * The browser fetches and executes the IIFE bundle; the promise resolves/rejects via load/error events.
 * The script accesses DWC APIs via `window.DWC` (set up by exposeGlobalAPI).
 */
function loadExternalJS(pluginId: string, url: string): Promise<void> {
	return new Promise<void>((resolve, reject) => {
		const script = document.createElement("script");
		script.setAttribute("data-dwc-plugin", pluginId);
		script.src = url;
		script.onload = () => resolve();
		script.onerror = () => reject(new Error(`Failed to load JS "${url}" for plugin "${pluginId}"`));
		document.head.appendChild(script);
	});
}

// #endregion

// #region Global API for external plugins
// `window.DWC` - the runtime surface external plugin bundles import against - is built in
// global-api.ts from the live module namespaces, so it cannot drift from what the plugin builder
// externalises. ensurePluginExtras() above augments its component maps once the lazy chunks arrive

// #endregion
