/**
 * plugins/index.ts
 *
 * DWC Plugin Loader
 *
 * Handles loading both built-in and external plugins:
 *
 * Built-in plugins are part of the same Vite build. They are auto-discovered
 * at build time by vite-plugin-dwc-plugins and lazily imported. Because they
 * share the module graph, they simply import what they need directly:
 *
 *   import { registerRoute } from "@/plugins";
 *   import MyPage from "./MyPage.vue";
 *   registerRoute(MyPage, { Plugins: { MyPage: { icon: "mdi-...", caption: "...", path: "/Plugins/MyPage" } } });
 *
 * External plugins are precompiled IIFE bundles fetched at runtime from the
 * machine. They are built with DWC's shared libraries marked as externals,
 * mapped to `window.DWC`. This lets them use the same API:
 *
 *   const { registerRoute } = DWC;
 *   registerRoute(MyPage, { ... });
 *
 * The global `window.DWC` object is set up by `initPluginSystem()` and exposes
 * the plugin registration functions, stores, Vue, vue-router, and i18n.
 */

import type { Component } from "vue";
import type { RouteRecordRaw, Router } from "vue-router";
import type { ModelCollection } from "@duet3d/objectmodel";

import type DwcPlugin from "./DwcPlugin";
import type { ContextMenuItem } from "@/stores/ui";

import * as Vue from "vue";
import * as VueRouter from "vue-router";
import * as Pinia from "pinia";
import * as VueI18n from "vue-i18n";
import * as ObjectModel from "@duet3d/objectmodel";
import * as Connectors from "@duet3d/connectors";

// @ts-ignore — virtual module generated by vite/dwc-plugins, replacement for "imports.ts"
import plugins from "virtual:dwc-builtin-plugins";

import Events from "@/utils/events";
import i18n from "@/i18n";

import { registerPluginData, setPluginData, PluginDataType } from "@/stores";
import { useSettingsStore } from "@/stores/settings";
import { useMachineStore } from "@/stores/machine";
import { useCacheStore } from "@/stores/cache";
import { useUiStore, ContextMenuType } from "@/stores/ui";

import packageInfo from "../../package.json";

// ─── Built-in plugin registry ────────────────────────────────────────

const builtInPlugins: ModelCollection<DwcPlugin> = plugins;

// ─── Manifest validation ─────────────────────────────────────────────

/**
 * Validate a plugin manifest.
 * @param manifest Plugin manifest to check
 * @returns Whether the manifest is valid
 */
export function checkManifest(manifest: { id: string; name: string; author: string; version: string }): boolean {
	if (!manifest.id || manifest.id.trim() === "" || manifest.id.length > 32) {
		console.warn("Invalid plugin identifier");
		return false;
	}
	if (manifest.id.split("").some(c => !/[a-zA-Z0-9 .\-_]/.test(c))) {
		console.warn("Illegal plugin identifier");
		return false;
	}
	if (!manifest.name || manifest.name.trim() === "" || manifest.name.length > 64) {
		console.warn("Invalid plugin name");
		return false;
	}
	if (manifest.name.split("").some(c => !/[a-zA-Z0-9 .\-_]/.test(c))) {
		console.warn("Illegal plugin name");
		return false;
	}
	if (!manifest.author || manifest.author.trim() === "") {
		console.warn("Missing author");
		return false;
	}
	if (!manifest.version || manifest.version.trim() === "") {
		console.warn("Missing version");
		return false;
	}
	return true;
}

/**
 * Perform a version compatibility check.
 * Compares version segments up to the shorter of the two strings.
 * @param actual Actual version (e.g. "3.6.0")
 * @param required Required version (e.g. "3.6")
 * @returns Whether the actual version satisfies the required version
 */
export function checkVersion(actual: string, required: string): boolean {
	if (!required) {
		return true;
	}
	const actualParts = actual.split(/[+.\-ab]/);
	const requiredParts = required.split(/[+.\-ab]/);
	for (let i = 0; i < Math.min(actualParts.length, requiredParts.length); i++) {
		if (actualParts[i] !== requiredParts[i]) {
			return false;
		}
	}
	return true;
}

// ─── State ───────────────────────────────────────────────────────────

/**
 * Set of currently loaded plugin IDs
 */
const loadedPlugins = new Set<string>();

/**
 * Vue Router instance, set during initialisation
 */
let _router: Router | null = null;

/**
 * Menu categories registered by plugins
 */
export interface MenuCategory {
	icon: string;
	caption: string | (() => string);
	translated: boolean;
	pages: Array<MenuItem>;
}

/**
 * Menu item registered by a plugin
 */
export interface MenuItem {
	icon: string;
	caption: string | (() => string);
	path: string;
	component: Component;
	translated?: boolean;
	condition?: boolean | (() => boolean);
}

const _menuCategories = new Map<string, MenuCategory>();

// ─── Initialisation ──────────────────────────────────────────────────

/**
 * Initialise the plugin system. Must be called once during app startup
 * before any plugins are loaded.
 *
 * Sets up the global `window.DWC` object so that external plugins can
 * access DWC APIs at runtime.
 *
 * @param router Vue Router instance
 */
export function initPluginSystem(router: Router) {
	_router = router;
	exposeGlobalAPI();
}

// ─── Plugin registration API ─────────────────────────────────────────
// These functions are called directly by plugins (both built-in and external).

/**
 * Register a new route and menu item.
 *
 * Follows the same convention as the previous DWC:
 *   registerRoute(Component, { CategoryName: { PageName: { icon, caption, path, condition? } } })
 *
 * @param component Vue component to render
 * @param route Route descriptor: { [category]: { [name]: { icon, caption, path, condition?, translated? } } }
 */
export function registerRoute(
	component: Component,
	route: Record<string, Record<string, { icon: string; caption: string | (() => string); path: string; condition?: boolean | (() => boolean); translated?: boolean }>>
) {
	if (!_router) {
		throw new Error("Plugin system not initialised");
	}

	const category = Object.keys(route)[0];
	const name = Object.keys(route[category])[0];
	const descriptor = route[category][name];

	// Build menu item
	const menuItem: MenuItem = {
		icon: descriptor.icon,
		caption: descriptor.caption,
		path: descriptor.path,
		component,
		translated: descriptor.translated ?? false,
		condition: descriptor.condition ?? true,
	};

	// Ensure category exists
	if (!_menuCategories.has(category)) {
		_menuCategories.set(category, {
			icon: "mdi-puzzle",
			caption: `menu.${category.toLowerCase()}.caption`,
			translated: false,
			pages: [],
		});
	}

	// Add to category
	_menuCategories.get(category)!.pages.push(menuItem);

	// Register vue-router route
	_router.addRoute({
		path: descriptor.path,
		component,
	} as RouteRecordRaw);
}

/**
 * Register a new menu category
 * @param name Internal name of the category
 * @param icon MDI icon string
 * @param caption Display caption (i18n key or getter function)
 * @param translated Whether the caption is already translated
 */
export function registerCategory(name: string, icon: string, caption: string | (() => string), translated = false) {
	if (!_menuCategories.has(name)) {
		_menuCategories.set(name, {
			icon,
			caption,
			translated,
			pages: [],
		});
	}
}

/**
 * Register a context menu item (e.g., on the job file list)
 * @param name Caption of the context menu item
 * @param path Optional route path to navigate to on click
 * @param icon MDI icon string
 * @param action Global event to trigger on click
 * @param contextMenuType Target of the context menu item
 */
export function registerPluginContextMenuItem(name: string | (() => string), path: string | undefined, icon: string, action: string, contextMenuType: ContextMenuType) {
	useUiStore().registerContextMenuItem({
		name,
		path,
		icon,
		action,
		contextMenuType,
	} as ContextMenuItem);
}

// ─── Query API ───────────────────────────────────────────────────────

/**
 * Get all registered built-in plugin entries
 */
export function getBuiltInPlugins() {
	return builtInPlugins;
}

/**
 * Get the set of currently loaded plugin IDs
 */
export function getLoadedPlugins(): ReadonlySet<string> {
	return loadedPlugins;
}

/**
 * Check whether a plugin is currently loaded
 */
export function isPluginLoaded(id: string): boolean {
	return loadedPlugins.has(id);
}

/**
 * Check whether a plugin is a built-in plugin
 */
export function isPluginBuiltIn(id: string): boolean {
	return builtInPlugins.some(p => p.id === id);
}

/**
 * Get all menu categories registered by plugins
 */
export function getMenuCategories(): ReadonlyMap<string, MenuCategory> {
	return _menuCategories;
}

// ─── Loading ─────────────────────────────────────────────────────────

/**
 * Load and initialise a single DWC plugin by ID.
 *
 * Checks built-in plugins first, then falls back to external.
 *
 * @param id Plugin ID
 * @param saveSettings Whether to persist the enabled state
 */
export async function loadDwcPlugin(id: string, saveSettings = true): Promise<void> {
	if (loadedPlugins.has(id)) {
		console.warn(`Plugin "${id}" is already loaded`);
		return;
	}

	const builtIn = builtInPlugins.find(p => p.id === id);
	if (builtIn) {
		await loadBuiltInPlugin(builtIn);
	} else {
		await loadExternalPlugin(id);
	}

	if (saveSettings) {
		useSettingsStore().dwcPluginLoaded(id);
	}

	Events.emit("dwcPluginLoaded", id);
}

/**
 * Load all enabled DWC plugins, reporting progress via events.
 */
export async function loadDwcPlugins(): Promise<void> {
	const settingsStore = useSettingsStore();

	if (settingsStore.enabledPlugins.length === 0) {
		return;
	}

	Events.emit("dwcPluginsLoading", [...settingsStore.enabledPlugins]);

	for (const id of settingsStore.enabledPlugins) {
		try {
			await loadDwcPlugin(id, false);
		} catch (e) {
			console.warn(`Failed to load plugin "${id}":`, e);
			Events.emit("dwcPluginLoadError", { id, error: e });
		}
	}

	Events.emit("dwcPluginsLoaded", [...settingsStore.enabledPlugins]);
}

/**
 * Unload a plugin (best-effort — removes tracking and settings entry)
 * @param id Plugin ID
 */
export async function unloadDwcPlugin(id: string): Promise<void> {
	if (!loadedPlugins.has(id)) {
		return;
	}

	loadedPlugins.delete(id);

	useSettingsStore().disableDwcPlugin(id);

	Events.emit("dwcPluginUnloaded", id);
}

// ─── Built-in plugin loading ─────────────────────────────────────────

/**
 * Load a built-in plugin by executing its dynamic import.
 * The module's side effects handle all registration.
 */
async function loadBuiltInPlugin(plugin: DwcPlugin): Promise<void> {
	await plugin.loadDwcResources();
	loadedPlugins.add(plugin.id);
}

// ─── External plugin loading ─────────────────────────────────────────

/**
 * Load an external plugin by fetching its JS/CSS from the machine.
 *
 * External plugins are IIFE bundles compiled with DWC's shared libraries
 * (vue, vue-router, pinia, DWC's own API) marked as externals. At runtime
 * those resolve to properties on `window.DWC`, so the plugin code can call
 * the same registration functions as built-in plugins.
 */
async function loadExternalPlugin(id: string): Promise<void> {
	const machineStore = useMachineStore();
	const machinePlugin = machineStore.model.plugins.get(id);

	if (!machinePlugin) {
		throw new Error(`Plugin "${id}" not found in built-in registry or machine plugins`);
	}

	// Validate manifest
	if (!checkManifest(machinePlugin)) {
		throw new Error(`Plugin "${id}" has an invalid manifest`);
	}

	// Version compatibility check
	if (machinePlugin.dwcVersion && !checkVersion(packageInfo.version, machinePlugin.dwcVersion)) {
		throw new Error(
			`Plugin "${id}" requires DWC version ${machinePlugin.dwcVersion}, ` +
			`current is ${packageInfo.version}`
		);
	}

	// Check dependencies
	for (const dep of machinePlugin.dwcDependencies) {
		if (!loadedPlugins.has(dep)) {
			throw new Error(`Plugin "${id}" depends on "${dep}" which is not loaded`);
		}
	}

	// Separate JS and CSS files
	const jsFiles = machinePlugin.dwcFiles.filter((f: string) => f.endsWith(".js"));
	const cssFiles = machinePlugin.dwcFiles.filter((f: string) => f.endsWith(".css"));

	if (jsFiles.length === 0) {
		throw new Error(`Plugin "${id}" has no JS entry in dwcFiles`);
	}

	const baseURL = process.env.BASE_URL ?? '/';

	// Load CSS first
	for (const cssFile of cssFiles) {
		await loadExternalCSS(id, baseURL + cssFile);
	}

	// Load and execute JS
	for (const jsFile of jsFiles) {
		await loadExternalJS(id, baseURL + jsFile);
	}

	loadedPlugins.add(id);
}

/**
 * Load a CSS file for an external plugin by injecting a <link> element.
 * The browser fetches the resource; the promise resolves/rejects via load/error events.
 */
function loadExternalCSS(pluginId: string, url: string): Promise<void> {
	return new Promise<void>((resolve, reject) => {
		const link = document.createElement("link");
		link.rel = "stylesheet";
		link.setAttribute("data-dwc-plugin", pluginId);
		link.href = url;
		link.onload = () => resolve();
		link.onerror = () => reject(new Error(`Failed to load CSS "${url}" for plugin "${pluginId}"`));
		document.head.appendChild(link);
	});
}

/**
 * Load a JS file for an external plugin by injecting a <script> element.
 * The browser fetches and executes the IIFE bundle; the promise resolves/rejects via load/error events.
 * The script accesses DWC APIs via `window.DWC` (set up by exposeGlobalAPI).
 */
function loadExternalJS(pluginId: string, url: string): Promise<void> {
	return new Promise<void>((resolve, reject) => {
		const script = document.createElement("script");
		script.setAttribute("data-dwc-plugin", pluginId);
		script.src = url;
		script.onload = () => resolve();
		script.onerror = () => reject(new Error(`Failed to load JS "${url}" for plugin "${pluginId}"`));
		document.head.appendChild(script);
	});
}

// ─── Global API for external plugins ─────────────────────────────────

/**
 * Expose DWC's plugin API on `window.DWC` so that external plugin bundles
 * (compiled with these modules marked as externals) can access them at runtime.
 *
 * External plugins are built as IIFE bundles with rollup externals like:
 *   external: ["DuetWebControl", "vue", "vue-router", "pinia", ...]
 *   globals:  { "DuetWebControl": "DWC", "vue": "DWC.Vue", ... }
 *
 * This gives external plugins the same import experience as built-in ones.
 */
function exposeGlobalAPI() {
	(window as any).DWC = {
		// Plugin registration
		registerRoute,
		registerCategory,
		registerPluginContextMenuItem,

		// Plugin data
		registerPluginData,
		setPluginData,
		PluginDataType,

		// Stores
		useSettingsStore,
		useMachineStore,
		useCacheStore,
		useUiStore,
		ContextMenuType,

		// Events
		Events,

		// Vue ecosystem (mapped as globals for external plugin builds)
		Vue,
		VueRouter,
		Pinia,
		VueI18n,
		ObjectModel,
		Connectors,

		// i18n
		i18n,
	};
}
