/**
 * dwc-plugins.ts
 *
 * Vite plugin that auto-discovers built-in DWC plugins at build/dev time.
 *
 * It scans subdirectories of src/plugins/ for plugin.json manifests,
 * then generates a virtual module (or rewrites src/plugins/builtins.ts)
 * containing lazy-load import entries for each discovered plugin.
 *
 * Usage in vite.config.mts:
 *   import dwcPlugins from './vite-plugin-dwc-plugins'
 *   plugins: [ dwcPlugins(), ... ]
 *
 * Built-in plugin directory structure:
 *   src/plugins/
 *     MyPlugin/
 *       plugin.json     <- manifest
 *       index.ts        <- entry point (default export: init function)
 *       blacklist       <- if present, plugin is skipped
 */

import { readdirSync, existsSync, readFileSync } from "fs";
import { resolve, join } from "path";
import type { Plugin as VitePlugin } from "vite";

interface PluginEntry {
	id: string;
	manifest: Record<string, any>;
	entryFile: string;       // relative to src/plugins/, e.g. "HeightMap/index"
}

const VIRTUAL_MODULE_ID = "virtual:dwc-builtin-plugins";
const RESOLVED_VIRTUAL_MODULE_ID = "\0" + VIRTUAL_MODULE_ID;

export default function dwcPlugins(): VitePlugin {
	const pluginsDir = resolve(import.meta.dirname, "../src/plugins");

	// Built-in plugin manifests use "auto" to mean "track the DWC version" so they don't have
	// to be bumped every release; resolved at build time from package.json
	const pkgVersion = (() => {
		try {
			return JSON.parse(readFileSync(resolve(import.meta.dirname, "../package.json"), "utf-8")).version as string;
		} catch {
			return "0.0.0";
		}
	})();

	function discoverPlugins(): PluginEntry[] {
		const entries: PluginEntry[] = [];

		if (!existsSync(pluginsDir)) {
			return entries;
		}

		for (const dir of readdirSync(pluginsDir, { withFileTypes: true })) {
			if (!dir.isDirectory()) continue;
			const pluginDir = join(pluginsDir, dir.name);

			// Skip blacklisted plugins
			if (existsSync(join(pluginDir, "blacklist"))) continue;

			// Must have a plugin.json
			const manifestPath = join(pluginDir, "plugin.json");
			if (!existsSync(manifestPath)) continue;

			let manifest: Record<string, any>;
			try {
				manifest = JSON.parse(readFileSync(manifestPath, "utf-8"));
			} catch {
				console.warn(`[dwc-plugins] Failed to parse ${manifestPath}`);
				continue;
			}

			// Resolve the "auto" placeholder for version + dwcVersion against the DWC package version
			for (const key of ["version", "dwcVersion"]) {
				if (manifest[key] === "auto") {
					manifest[key] = pkgVersion;
				}
			}

			// Find entry point: index.ts > index.js > dwc-src/index.ts > dwc-src/index.js > src/index.ts > src/index.js
			const candidates = [
				"index.ts",
				"index.js",
				join("dwc-src", "index.ts"),
				join("dwc-src", "index.js"),
				join("src", "index.ts"),
				join("src", "index.js"),
			];

			let entryFile: string | null = null;
			for (const candidate of candidates) {
				if (existsSync(join(pluginDir, candidate))) {
					// Strip the extension and force forward slashes - entryFile is interpolated
					// into an ESM import specifier, which is invalid with Windows backslashes
					entryFile = join(dir.name, candidate).replace(/\.\w+$/, "").replace(/\\/g, "/");
					break;
				}
			}

			if (!entryFile) {
				console.warn(`[dwc-plugins] No entry point found for plugin "${dir.name}"`);
				continue;
			}

			entries.push({
				id: manifest.id || dir.name,
				manifest,
				entryFile,
			});
		}

		return entries;
	}

	function generateCode(plugins: PluginEntry[]): string {
		const entries = plugins.map((p) => {
			const fields = Object.entries(p.manifest)
				.map(([k, v]) => `        ${k}: ${JSON.stringify(v)}`)
				.join(",\n");
			return `    {\n${fields},\n        loadDwcResources: () => import("@/plugins/${p.entryFile}")\n    }`;
		});

		return [
			`// Auto-generated by vite-plugin-dwc-plugins - DO NOT EDIT`,
			`import { initCollection } from "@duet3d/objectmodel";`,
			`import DwcPlugin from "@/plugins/DwcPlugin";`,
			``,
			`export default initCollection(DwcPlugin, [`,
			entries.join(",\n"),
			`]);`,
			``,
		].join("\n");
	}

	let plugins: PluginEntry[] = [];

	return {
		name: "vite-plugin-dwc-plugins",
		enforce: "pre",

		buildStart() {
			plugins = discoverPlugins();
		},

		// rolldown hook filters: only invoke the JS callback for our virtual id, so we don't
		// pay a Rust->JS hop on every other module's resolve / load (cuts this plugin's share
		// of PLUGIN_TIMINGS from ~50% on full builds because monaco-editor alone has thousands
		// of internal modules). resolveId requires a regex - string filters aren't supported there
		resolveId: {
			filter: { id: /^virtual:dwc-builtin-plugins$/ },
			handler(id) {
				if (id === VIRTUAL_MODULE_ID) {
					return RESOLVED_VIRTUAL_MODULE_ID;
				}
			},
		},

		load: {
			filter: { id: /^\0virtual:dwc-builtin-plugins$/ },
			handler(id) {
				if (id === RESOLVED_VIRTUAL_MODULE_ID) {
					return generateCode(plugins);
				}
			},
		},

		// In dev mode, re-discover plugins when files change in the plugins dir
		configureServer(server) {
			server.watcher.add(pluginsDir);
		},

		handleHotUpdate({ file }) {
			if (file.includes("/src/plugins/") && file.endsWith("plugin.json")) {
				plugins = discoverPlugins();
				// Invalidate the virtual module so it gets regenerated
				return [];
			}
		},
	};
}
