/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ATXPanel: typeof import('./components/panels/ATXPanel.vue')['default']
    CNCAxesPosition: typeof import('./components/panels/CNCAxesPosition.vue')['default']
    CNCContainerPanel: typeof import('./components/panels/CNCContainerPanel.vue')['default']
    CNCDashboardPanel: typeof import('./components/panels/CNCDashboardPanel.vue')['default']
    CNCMovementPanel: typeof import('./components/panels/CNCMovementPanel.vue')['default']
    CodeButton: typeof import('./components/buttons/CodeButton.vue')['default']
    CodeInput: typeof import('./components/inputs/CodeInput.vue')['default']
    ConfigUpdatedDialog: typeof import('./components/dialogs/ConfigUpdatedDialog.vue')['default']
    ConfirmDialog: typeof import('./components/dialogs/ConfirmDialog.vue')['default']
    ConnectButton: typeof import('./components/buttons/ConnectButton.vue')['default']
    ConnectDialog: typeof import('./components/dialogs/ConnectDialog.vue')['default']
    ConnectionProgressDialog: typeof import('./components/dialogs/ConnectionProgressDialog.vue')['default']
    ControlAllDropdown: typeof import('./components/panels/ToolsPanel/ControlAllDropdown.vue')['default']
    ControlInput: typeof import('./components/inputs/ControlInput.vue')['default']
    ControlList: typeof import('./components/panels/ToolsPanel/ControlList/ControlList.vue')['default']
    EmergencyButton: typeof import('./components/buttons/EmergencyButton.vue')['default']
    EventList: typeof import('./components/lists/EventList.vue')['default']
    ExtraSensorList: typeof import('./components/panels/ToolsPanel/ExtraSensorList.vue')['default']
    ExtrudePanel: typeof import('./components/panels/ExtrudePanel.vue')['default']
    ExtrusionFactorsPanel: typeof import('./components/panels/ExtrusionFactorsPanel.vue')['default']
    FanPanel: typeof import('./components/panels/FanPanel.vue')['default']
    FansPanel: typeof import('./components/panels/FansPanel.vue')['default']
    FFFContainerPanel: typeof import('./components/panels/FFFContainerPanel.vue')['default']
    FFFDashboardPanel: typeof import('./components/panels/FFFDashboardPanel.vue')['default']
    FilamentDialog: typeof import('./components/dialogs/FilamentDialog.vue')['default']
    FileList: typeof import('./components/lists/FileList.vue')['default']
    FirmwareUpdateDialog: typeof import('./components/dialogs/FirmwareUpdateDialog.vue')['default']
    HeaterRows: typeof import('./components/panels/ToolsPanel/ControlList/HeaterRows.vue')['default']
    IncompatibleVersionsDialog: typeof import('./components/dialogs/IncompatibleVersionsDialog.vue')['default']
    InputDialog: typeof import('./components/dialogs/InputDialog.vue')['default']
    JobControlPanel: typeof import('./components/panels/JobControlPanel.vue')['default']
    JobDataPanel: typeof import('./components/panels/JobDataPanel.vue')['default']
    JobEstimationsPanel: typeof import('./components/panels/JobEstimationsPanel.vue')['default']
    JobFileList: typeof import('./components/lists/JobFileList.vue')['default']
    JobInfoPanel: typeof import('./components/panels/JobInfoPanel.vue')['default']
    JobProgress: typeof import('./components/misc/JobProgress.vue')['default']
    JobThumbnailCell: typeof import('./components/lists/JobThumbnailCell.vue')['default']
    LayerChart: typeof import('./components/charts/LayerChart.vue')['default']
    ListEditor: typeof import('./components/inputs/ListEditor.vue')['default']
    MacroList: typeof import('./components/lists/MacroList.vue')['default']
    MeshEditDialog: typeof import('./components/dialogs/MeshEditDialog.vue')['default']
    MessageBoxDialog: typeof import('./components/dialogs/MessageBoxDialog.vue')['default']
    MonacoEditor: typeof import('./components/editor/MonacoEditor.vue')['default']
    MovementPanel: typeof import('./components/panels/MovementPanel.vue')['default']
    NavMenuBadge: typeof import('./components/misc/NavMenuBadge.vue')['default']
    NotificationDisplay: typeof import('./components/misc/NotificationDisplay.vue')['default']
    PanelLink: typeof import('./components/misc/PanelLink.vue')['default']
    PercentageInput: typeof import('./components/inputs/PercentageInput.vue')['default']
    PluginInstallDialog: typeof import('./components/dialogs/PluginInstallDialog.vue')['default']
    ResetHeaterFaultDialog: typeof import('./components/dialogs/ResetHeaterFaultDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpeedFactorPanel: typeof import('./components/panels/SpeedFactorPanel.vue')['default']
    SpindleSpeedPanel: typeof import('./components/panels/SpindleSpeedPanel.vue')['default']
    StatusLabel: typeof import('./components/misc/StatusLabel.vue')['default']
    StatusPanel: typeof import('./components/panels/StatusPanel.vue')['default']
    TemperatureChart: typeof import('./components/charts/TemperatureChart.vue')['default']
    ThumbnailImg: typeof import('./components/misc/ThumbnailImg.vue')['default']
    ToolRows: typeof import('./components/panels/ToolsPanel/ControlList/ToolRows.vue')['default']
    ToolsPanel: typeof import('./components/panels/ToolsPanel/ToolsPanel.vue')['default']
    UploadButton: typeof import('./components/buttons/UploadButton.vue')['default']
    WebcamPanel: typeof import('./components/panels/WebcamPanel.vue')['default']
    ZBabystepPanel: typeof import('./components/panels/ZBabystepPanel.vue')['default']
  }
}
