/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CodeButton: typeof import('./components/buttons/CodeButton.vue')['default']
    CodeInput: typeof import('./components/inputs/CodeInput.vue')['default']
    ConnectDialog: typeof import('./components/dialogs/ConnectDialog.vue')['default']
    ConnectionProgressDialog: typeof import('./components/dialogs/ConnectionProgressDialog.vue')['default']
    EventList: typeof import('./components/lists/EventList.vue')['default']
    MessageBoxDialog: typeof import('./components/dialogs/MessageBoxDialog.vue')['default']
    NotificationDisplay: typeof import('./components/misc/NotificationDisplay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThumbnailImg: typeof import('./components/misc/ThumbnailImg.vue')['default']
  }
}
