/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...notFound]': RouteRecordInfo<
      '/[...notFound]',
      '/:notFound(.*)',
      { notFound: ParamValue<true> },
      { notFound: ParamValue<false> },
      | never
    >,
    '/Console': RouteRecordInfo<
      '/Console',
      '/Console',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Dashboard': RouteRecordInfo<
      '/Dashboard',
      '/Dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Explorer/[[tab]]/[[volume]]/[[...path]]': RouteRecordInfo<
      '/Explorer/[[tab]]/[[volume]]/[[...path]]',
      '/Explorer/:tab?/:volume?/:path(.*)?',
      { path?: ParamValueZeroOrOne<true>, tab?: ParamValueZeroOrOne<true>, volume?: ParamValueZeroOrOne<true> },
      { path?: ParamValueZeroOrOne<false>, tab?: ParamValueZeroOrOne<false>, volume?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/Job/Status': RouteRecordInfo<
      '/Job/Status',
      '/Job/Status',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Job/Webcam': RouteRecordInfo<
      '/Job/Webcam',
      '/Job/Webcam',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Jobs/[[volume]]/[[...path]]': RouteRecordInfo<
      '/Jobs/[[volume]]/[[...path]]',
      '/Jobs/:volume?/:path(.*)?',
      { path?: ParamValueZeroOrOne<true>, volume?: ParamValueZeroOrOne<true> },
      { path?: ParamValueZeroOrOne<false>, volume?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/Macros': RouteRecordInfo<
      '/Macros',
      '/Macros',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Settings/[[tab]]': RouteRecordInfo<
      '/Settings/[[tab]]',
      '/Settings/:tab?',
      { tab?: ParamValueZeroOrOne<true> },
      { tab?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/Settings/Plugins': RouteRecordInfo<
      '/Settings/Plugins',
      '/Plugins',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Temperatures': RouteRecordInfo<
      '/Temperatures',
      '/Temperatures',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...notFound].vue': {
      routes:
        | '/[...notFound]'
      views:
        | never
      pathParamNames:
        | 'notFound'
    }
    'src/pages/Console.vue': {
      routes:
        | '/Console'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/Dashboard.vue': {
      routes:
        | '/Dashboard'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/Explorer/[[tab]]/[[volume]]/[[...path]].vue': {
      routes:
        | '/Explorer/[[tab]]/[[volume]]/[[...path]]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/Job/Status.vue': {
      routes:
        | '/Job/Status'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/Job/Webcam.vue': {
      routes:
        | '/Job/Webcam'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/Jobs/[[volume]]/[[...path]].vue': {
      routes:
        | '/Jobs/[[volume]]/[[...path]]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/Macros.vue': {
      routes:
        | '/Macros'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/Settings/[[tab]].vue': {
      routes:
        | '/Settings/[[tab]]'
      views:
        | never
      pathParamNames:
        | 'tab'
    }
    'src/pages/Settings/Plugins.vue': {
      routes:
        | '/Settings/Plugins'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/Temperatures.vue': {
      routes:
        | '/Temperatures'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
